print("hello world")
print("cats are cool")
print('dogs are cool')
print("some girl just asked me to borrow a mac charger lol in the library")
print("hope she doesn't steal it-- !!")
print("no idea how long it's been but i hope she returns my charger bc i need to pee")
